### ISSUE TITLE
Collision detection using libstage v4.1.1

### ISSUE THREAD

**Issue by zombiecrab** [rtv/Stage#26]
With a vanilla installation of Stage v4.1.1 I find that agents can pass through obstacles.

Recreating error:

head to examples folder and edit line 152 of stest.cc to:
robots[idx].position->SetSpeed( 0.5, side_speed, 0.0 );

When stest.cc is compiled and run with the command:

stest simple.world 1

Thew agent can be seen detecting obstacles but not colliding with them, instead the agent just passes through them. 

Parameter obstacle_return in pioneer.inc for definition of pioneer_base is set to 1. As far as I know this is the only parameter involved that could effect collision detection.

This is being run on Ubuntu 10.04 LTS.

I will create a new virtual machine tonight and see if I still get this error.

**Comment by rtv** [comment]
Not seeing an answer or repeats in 5 years, I close the issue.
