### ISSUE TITLE
SFU_800x600.png required by worlds/large.world, removed from repository

### ISSUE THREAD

**Issue by RafBerkvens** [rtv/Stage#30]
The file worlds/bitmaps/SFU_800x600.png, which is still available in 59d66b44f1b7df3eeb8d9997f32b94f8cefb582e, was removed in later versions. However, the file world/large.world still depends on this file. 

Can either the file large.world be updated, or the file SFU_800x600.png be resubmitted, so that fresh Stage installs do not return an error when trying some code?

**Comment by rtv** [comment]
updated large world to use the huge map which is supplied.

 bitmap "bitmaps/SFU_1200x615.png"
