### ISSUE TITLE
Stage 4.1.1 display problem in Ubuntu

### ISSUE THREAD

**Issue by bombilee** [rtv/Stage#37]
Hi,
I have Stage 4.1.1 install in both Ubuntu 12.04 64bit (Vmware Fusion 5.0.2) & Mac 10.6.8
I try several ways to install Stage4.1.1 in Ubuntu ( with ros or directly from github). I still can't get simple world file display correctly in Ubuntu.  I really don't know what cause it. I have same problem on every Ubuntu I installed, too( not in Vmware).  The simple.world is the one come with stage 4.1.1 without any modification. Please let me know if you need for information on my setup. Thanks.
Here is the screen shot for it.
![ScreenshotUbuntu-Mac](https://f.cloud.github.com/assets/512193/330780/999aad4e-9bd7-11e2-97b5-1490da09b93e.jpg)

**Comment by rtv** [comment]
Seems to be fixed. I don't see the behaviour. Please re-open if anyone sees it.
