### ISSUE TITLE
area computation in p_blobfinder

### ISSUE THREAD

**Issue by knickels** [rtv/Stage#41]
In p_blobfinder.cc:102, area (a uint32) is set to dx*dy.
But dy = blobs[b].top - blobs[b].bottom (a negative number in my case at least).
So area is set to a negative number.

With an (int) cast in the calling program, I get the "correct" negative area back, so I think that the data are passed correctly.

Not sure what the best way to fix this would be - to redefine dy as bottom-top, to add an abs() to dy?  Is top ever > bottom?

**Comment by rtv** [comment]
Fixed in master. Will appear  in 4.2.0 release.
