### ISSUE TITLE
"invalid suffix on literal" Warnings C++11

### ISSUE THREAD

**Issue by Rookfighter** [rtv/Stage#47]
When using C++11, I get a lot of warnings of the type "warning: invalid suffix on literal; C++11 requires a space between literal and identifier".
These are caused by the `PRINT_*` macros in stage.hh beginning in line 650 up to line 689.
The macros all look like this:

```
#define PRINT_ERR(m) fprintf( stderr, "\033[41merr\033[0m: "m" (%s %s)\n", __FILE__, __FUNCTION__)
```

The message `m` should be seperated by a blank space from the surrounding strings. C++11 has special syntax for characters immediately following a string literal, so these may be interpreted differently.
In my case I altered the stage.hh, so all `m` are seperated by a blank space from the strings and it works just fine (as expected).
This should probably be changed in the master as this is not much work and in the future more people will use C++11.

**Comment by majorx234** [comment]
or should be seperated with a # 
https://github.com/rtv/Stage/files/402145/stage.hh.diff.zip

**Comment by rtv** [comment]
Fixed in master.
