### ISSUE TITLE
Obtain Obstacle Co-ordinates from Stage to position VisualMarker in Rviz

### ISSUE THREAD

**Issue by ktiwari9** [rtv/Stage#52]
Hello there,
I am quite new to using Stage-Sim. I positioned a Model in the stage sim so that it behaves as an obstacle for the mobile robot. Now I want to obtain the co-ordinates of this obstacle from the stage sim and use this location to position a Rviz Marker such that when the user manually moves the obstacle in Stage-Sim the position of the RViz Marker is also updated.
Please advise how I can do this.

**Comment by rtv** [comment]
Not an issue, and possibly Stage-ROS specific. Please us the appropriate mailing list for user support.
