### ISSUE TITLE
Package version ":{version}" does not follow version conventions

### ISSUE THREAD

**Issue by u04617** [rtv/Stage#68]
I tried to use this package on ROS-Kinetic under Ubuntu 16.04. After cloning it, when I tried to catkin_make it, I got the following error. 

`Package version ":{version}" does not follow version conventions`

When I tried to remove all the other folders in my work space which were of Hydro, Indigo and Jade etc. still I got the same error. Please, help. How can I solve it?

**Comment by jpgr87** [comment]
Stage isn't a catkin package, you should just build it with cmake.
