### ISSUE TITLE
Increasing trail_length value badly affects world gui and trail footprint rendering

### ISSUE THREAD

**Issue by den4ix** [rtv/Stage#76]
Increasing trail_length value through world file or by means of recompiling Stage badly affects world gui map. In particular, the gui starts to hover, sometimes crash and doesn't properly visualize the trail footprint. To reproduce, just add trail_length 200, or some value more than 50 to the model properties and turn on Footprints under View bar.

**Comment by rtv** [comment]
fixed in master. Will appear in release 4.2.0.

In the process, I made trail length configurable per model.
